# Generated by Django 5.2.6 on 2025-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeFormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('asset', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loat_size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('risk_manage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('trade_result', models.CharField(max_length=200)),
                ('reason_for_trade', models.CharField(max_length=255)),
                ('emotions', models.CharField(max_length=255)),
                ('you_learned', models.CharField(blank=True, max_length=255, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
